Algoritmo "Problema Consumo"

Var

   DistanciaPercorrida : inteiro
   CombustivelGasto , ConsumoMedio : real
   



Inicio

   escreval("CALCULADORA CONSUMO MEDIO")
   escreval("---------------------------")
   escreval("Distancia Percorrida: ")
   leia(DistanciaPercorrida)
   escreval("Combustivel Gasto: ")
   leia(CombustivelGasto)
   ConsumoMedio <- DistanciaPercorrida/CombustivelGasto
   escreval("Consumo Medio = " , ConsumoMedio:8:3)





   
   
Fimalgoritmo